### ISSUE TITLE
Documentation for using in HTML page

### ISSUE THREAD

**Issue by explorerInfinite** [convergencelabs/codemirror-collab-ext#20]
Hi, I have CodeMirror used in my page and working well. I want to use this extension for user cursor cues. Is there any code examples for how to reference extension in the page and also in the code? Thanks.

**Comment by alalonde** [comment]
Yes, there are some links [here](https://examples.convergence.io/examples/codemirror/)

**Comment by explorerInfinite** [comment]
> Yes, there are some links [here](https://examples.convergence.io/examples/codemirror/)

Thanks for links. The link example shows ```
const remoteCursorManager = new CodeMirrorCollabExt.RemoteCursorManager({
  editor: editor,
  tooltips: true,
  tooltipDuration: 2
});
```

i am new to using CodeMirror and also npm installs. How does CodeMirrorCollabExt referenced in the page javascript. Is it a ` <link rel=""/>` that I need to use? Also, while installing in which folder should install? If you have a complete examaple handy that will be great. appreciate your help. Thanks.
